name:                optparse-applicative-cmdline-util
version:             0.2.0
homepage:            https://gitlab.com/slotThe/optparse-applicative-util
license:             AGPL-3
synopsis:            Utility functions for working with optparse-applicative
author:              Tony Zorman
maintainer:          soliditsallgood@mailbox.org
copyright:           2020–2022  Tony Zorman

ghc-options:
  -O2
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-prepositive-qualified-module

dependencies:
  - base                  >= 4.7      && < 5
  - optparse-applicative  >= 0.15.0.0 && < 0.17
  - attoparsec            >= 0.13.2.4 && < 0.15
  - text                  >= 1.2.4.0  && < 1.3

library:
  source-dirs: lib
