name:                optparse-applicative-cmdline-util
version:             0.2.0
homepage:            https://github.com/slotThe/optparse-applicative-cmdline-util
github:              slotThe/optparse-applicative-cmdline-util
license:             AGPL-3
synopsis:            Utility functions for working with optparse-applicative
description:         See README.md <https://gitlab.com/slotThe/optparse-applicative-util/-/blob/master/README.md here>
author:              Tony Zorman
maintainer:          soliditsallgood@mailbox.org
copyright:           2020–2022  Tony Zorman
category:            System, CLI, Options, Parsing

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-prepositive-qualified-module

dependencies:
  - base                  >= 4.7      && < 5
  - optparse-applicative  >= 0.15.0.0 && < 0.18
  - attoparsec            >= 0.13.2.4 && < 0.15
  - text                  >= 1.2.4.0  && < 1.3

library:
  source-dirs: lib
  exposed-modules:
    - Options.Applicative.CmdLine.Util
