name:                optparse-applicative-util
version:             0.1.0.0
homepage:            https://gitlab.com/slotThe/optparse-applicative-util
license:             AGPL-3
synopsis:            Utility functions for working with optparse-applicative
author:              slotThe
maintainer:          soliditsallgood@mailbox.org
copyright:           2020–2022  slotThe

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

dependencies:
  - base                  >= 4.7      && < 5
  - optparse-applicative  >= 0.15.0.0 && < 0.17
  - attoparsec            >= 0.13.2.4 && < 0.15
  - text                  >= 1.2.4.0  && < 1.3

library:
  source-dirs: lib
